export const GIT_IPC_CHANNELS = {
  status: "git:status",
  userEmail: "git:userEmail",
  stageFile: "git:stageFile",
  restoreFile: "git:restoreFile",
  restoreStagedFile: "git:restoreStagedFile",
  branches: "git:branches",
  switchBranch: "git:switchBranch",
  createBranch: "git:createBranch",
  branch: "git:branch",
  remoteBranches: "git:remoteBranches",
  commits: "git:commits",
  commitChange: "git:commitChange",
  showFileDiff: "git:showFileDiff",
  getCommitLog: "git:getCommitLog",
  checkout: "git:checkout",
  getRemotes: "git:getRemotes",
  addRemote: "git:addRemote",
  push: "git:push",
  pull: "git:pull",
  fetch: "git:fetch",
  headDiff: "git:headDiff",
  diffStat: "git:diffStat",
  diffNumstat: "git:diffNumstat",
};
